#ifndef PARSER_H
#define PARSER_H

/* Recursive descent parser (Top-Down Parser)
*   Is able to determine if a string is generated by a LL grammars (left-to-right, left-most derivation).
*   Those type of grammars have productions always starting with terminals.
*   A non-terminal's productions never start with the same terminal.
*/

/* Recognized grammar:
*
* S → if E then S else S
* S → begin S L
* S → print E
* L → end
* L → ; S L
* E → num = num
* 
* ps: note that this is a LL grammar.
*/

int parse();

#endif